# Generated by Django 4.0.4 on 2023-01-04 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_content_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
    ]
